sudo: false

language: r

cache: packages

install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat","covr"));devtools::install_deps("ooc")'

script:
  - Rscript -e 'devtools::check("ooc")'
  

r_packages:
  - covr
  
r_github_packages:
  - r-lib/covr

after_success:
  setwd("/home/travis/build/tzuliu/")
  - Rscript -e 'covr::codecov()'
