sudo: false

language: r

cache: packages

r_packages:
  - covr
 
install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"));devtools::install_deps("ooc")'

r_github_packages:
  - codecov/example-r

script:
  - Rscript -e 'devtools::check("ooc")'
 
after_success:
  - Rscript -e 'covr::codecov()'
