sudo: false

language: r

cache: packages

os:
  - osx

install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"));devtools::install_deps("ooc")'
 
#r_packages:
#  - covr

script:
  - Rscript -e 'devtools::check("ooc")'
  
r_github_packages:
  - jimhester/covr
#  - hadley/dplyr
#  - hadley/tidyr
#  - hadley/ggplot2
#  - ehrlinger/randomForestSRC

after_success:
  - Rscript -e 'covr::coveralls()'
