sudo: false

language: r

cache: packages

os:
  - osx

install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"));devtools::install_deps("ooc")'
 
#r_packages:
#  - covr

script:
  - Rscript -e 'devtools::check("ooc")'
  
r_github_packages:
  - jimhester/covr

after_success:
  after_success:
  # Only check test coverage for R = release and OS = linux.
  - test ${TRAVIS_OS_NAME} == "osx" && Rscript -e 'covr::codecov()'
