sudo: false

language: r

cache: packages

install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"));devtools::install_deps("ooc")'

script:
  - Rscript -e 'devtools::check("ooc")'
  
r_github_packages:
  - r-lib/covr
 
after_success:
  - Rscript -e 'covr::codecov()'
