sudo: false

language: r

cache: packages

install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"));devtools::install_deps("ooc")'

r_packages:
  - covr

r_github_packages:
  - codecov/example-r

after_success:
  - Rscript -e 'library(covr);codecov()'
